#!/usr/bin/env python3
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "bench/parsers/lexbor/utils/lexbor/html/data/entities.json"
OUT = Path(__file__).with_name("data.zig")
GENERATED_DIR = ROOT / "bench/entity_lookup/generated"
GPERF_INPUT = GENERATED_DIR / "named_entities.gperf"
GPERF_C = GENERATED_DIR / "named_entities.c"
GPERF_ZIG = GENERATED_DIR / "named_entities_gperf.zig"
NAMED_OUT = GENERATED_DIR / "named_entities.zig"
EMPTY = 0xFFFF


raw = json.loads(SOURCE.read_text())
items = [(key[1:].encode(), value["characters"].encode()) for key, value in raw.items()]
items.sort(key=lambda item: (len(item[0]), item[0]))

name_blob = bytearray()
value_blob = bytearray()
entries = []
for name, value in items:
    ns = len(name_blob)
    vs = len(value_blob)
    name_blob.extend(name)
    value_blob.extend(value)
    entries.append((ns, len(name), vs, len(value)))

def ints(values):
    return ",".join(str(value) for value in values)


with OUT.open("w") as out:
    out.write("// Generated by generate.py from the WHATWG entity table.\n")
    out.write("pub const empty: u16 = 0xffff;\n")
    out.write("pub const Entry = struct { name_start: u32, name_len: u8, value_start: u32, value_len: u8 };\n")
    out.write(f"pub const names = [_]u8{{{ints(name_blob)}}};\n")
    out.write(f"pub const values = [_]u8{{{ints(value_blob)}}};\n")
    out.write("pub const entries = [_]Entry{\n")
    for row in entries:
        out.write(f".{{.name_start={row[0]},.name_len={row[1]},.value_start={row[2]},.value_len={row[3]}}},\n")
    out.write("};\n")
hash_run = subprocess.run(
    ["zig", "run", str(Path(__file__).with_name("std_hashes.zig")), "-O", "ReleaseFast"],
    cwd=ROOT,
    text=True,
    capture_output=True,
    check=True,
)
std_hashes = [int(line) for line in hash_run.stderr.splitlines() if line.isdigit()]
if len(std_hashes) != len(items):
    raise RuntimeError(f"expected {len(items)} std hashes, got {len(std_hashes)}")

shards = [(0, 0, 0) for _ in range(33)]
slots = []
for length in range(2, 33):
    indexes = [i for i, item in enumerate(items) if len(item[0]) == length]
    if not indexes:
        continue
    cap = 1
    while cap * 7 < len(indexes) * 10:
        cap *= 2
    start = len(slots)
    table = [EMPTY] * cap
    for index in indexes:
        pos = std_hashes[index] & (cap - 1)
        while table[pos] != EMPTY:
            pos = (pos + 1) & (cap - 1)
        table[pos] = index
    slots.extend(table)
    shards[length] = (start, cap, cap - 1)

full_cap = 1
while full_cap * 7 < len(items) * 10:
    full_cap *= 2
full_slots = [EMPTY] * full_cap
for index, value_hash in enumerate(std_hashes):
    pos = value_hash & (full_cap - 1)
    while full_slots[pos] != EMPTY:
        pos = (pos + 1) & (full_cap - 1)
    full_slots[pos] = index

std_cap = 1
while std_cap * 80 // 100 < len(items):
    std_cap *= 2
std_slots = [EMPTY] * std_cap
std_meta = [0] * std_cap
for index, value_hash in enumerate(std_hashes):
    fingerprint = (value_hash >> 56) or 1
    pos = value_hash & (std_cap - 1)
    while std_meta[pos] != 0:
        pos = (pos + 1) & (std_cap - 1)
    std_slots[pos] = index
    std_meta[pos] = fingerprint

with OUT.open("a") as out:
    out.write("pub const Shard = struct { start: u16, cap: u16, mask: u16 };\n")
    out.write("pub const shards = [_]Shard{\n")
    for row in shards:
        out.write(f".{{.start={row[0]},.cap={row[1]},.mask={row[2]}}},\n")
    out.write("};\n")
    out.write(f"pub const slots = [_]u16{{{ints(slots)}}};\n")
    out.write(f"pub const full_hash_mask: u16 = {full_cap - 1};\n")
    out.write(f"pub const full_hash_slots = [_]u16{{{ints(full_slots)}}};\n")
    out.write(f"pub const std_hash_mask: u16 = {std_cap - 1};\n")
    out.write(f"pub const std_slots = [_]u16{{{ints(std_slots)}}};\n")
    out.write(f"pub const std_meta = [_]u8{{{ints(std_meta)}}};\n")
print(f"generated {OUT}: {len(items)} entries, {len(slots)} sharded Wyhash slots")

GENERATED_DIR.mkdir(parents=True, exist_ok=True)
with GPERF_INPUT.open("w") as out:
    out.write(r'''%language=ANSI-C
%readonly-tables
%global-table
%struct-type
%define lookup-function-name entity_lookup
%define hash-function-name entity_hash
%define word-array-name entity_wordlist
%define slot-name name
%compare-lengths
%compare-strncmp
%{
typedef __SIZE_TYPE__ size_t;
static int entity_compare(const char *a, const char *b, size_t len) {
  while (len--) {
    unsigned char ac = (unsigned char)*a++;
    unsigned char bc = (unsigned char)*b++;
    if (ac != bc) return (int)ac - (int)bc;
  }
  return 0;
}
#define strncmp entity_compare
#define memcmp entity_compare
%}
struct Entity { const char *name; unsigned short index; };
%%
''')
    for index, (name, _) in enumerate(items):
        out.write(f"{name.decode('ascii')},{index}\n")
    out.write("%%\n")

subprocess.run(["gperf", str(GPERF_INPUT), f"--output-file={GPERF_C}"], cwd=ROOT, check=True)
c_source = GPERF_C.read_text()
asso_match = re.search(
    r"static const unsigned short asso_values\[\]\s*=\s*\{(.*?)\n\s*\};",
    c_source,
    re.S,
)
if asso_match is None:
    raise RuntimeError("could not find gperf association values")
asso_values = [int(value) for value in re.findall(r"\d+", asso_match.group(1))]
translated = subprocess.run(
    ["zig", "translate-c", str(GPERF_C)], cwd=ROOT, text=True, capture_output=True, check=True
)
if "pub export fn entity_lookup" not in translated.stdout:
    raise RuntimeError("zig translate-c output no longer exposes the expected gperf lookup declaration")
translated_zig = translated.stdout.replace("pub export fn entity_lookup", "pub fn entity_lookup")
if "export fn" in translated_zig:
    raise RuntimeError("translated gperf output still contains an exported function")

tuned_compare = r'''const std = @import("std");

pub inline fn entity_compare(a: [*c]const u8, b: [*c]const u8, len: usize) bool {
    return std.mem.eql(u8, a[0..len], b[0..len]);
}
'''
translated_zig, count = re.subn(
    r"const __root.*?pub fn entity_compare\(.*?\n\}\npub const struct_Entity",
    tuned_compare + "pub const struct_Entity",
    translated_zig,
    count=1,
    flags=re.S,
)
if count != 1:
    raise RuntimeError("could not replace translated entity_compare")

tuned_hash = f'''// gperf emits unsigned short values, but C integer promotion makes the
// additions below at least int-width. Use u32 here to preserve that behavior
// in Zig and avoid safety-check overflows on arbitrary non-entity input.
const AssoValues = [_]u32{{{ints(asso_values)}}};

pub fn entity_hash(str: [*c]const u8, len: usize) u32 {{
    var hash: u32 = @intCast(len);
    switch (len) {{
        2 => {{}},
        3 => hash += AssoValues[@as(usize, str[2]) + 1],
        4 => hash += AssoValues[@as(usize, str[3]) + 5] + AssoValues[@as(usize, str[2]) + 1],
        5 => hash += AssoValues[@as(usize, str[4]) + 3] + AssoValues[@as(usize, str[3]) + 5] + AssoValues[@as(usize, str[2]) + 1],
        6 => hash += AssoValues[@as(usize, str[5]) + 2] + AssoValues[@as(usize, str[4]) + 3] + AssoValues[@as(usize, str[3]) + 5] + AssoValues[@as(usize, str[2]) + 1],
        7 => hash += AssoValues[@as(usize, str[6]) + 1] + AssoValues[@as(usize, str[5]) + 2] + AssoValues[@as(usize, str[4]) + 3] + AssoValues[@as(usize, str[3]) + 5] + AssoValues[@as(usize, str[2]) + 1],
        8...11 => hash += AssoValues[str[7]] + AssoValues[@as(usize, str[6]) + 1] + AssoValues[@as(usize, str[5]) + 2] + AssoValues[@as(usize, str[4]) + 3] + AssoValues[@as(usize, str[3]) + 5] + AssoValues[@as(usize, str[2]) + 1],
        12...13 => hash += AssoValues[str[11]] + AssoValues[str[7]] + AssoValues[@as(usize, str[6]) + 1] + AssoValues[@as(usize, str[5]) + 2] + AssoValues[@as(usize, str[4]) + 3] + AssoValues[@as(usize, str[3]) + 5] + AssoValues[@as(usize, str[2]) + 1],
        else => hash += AssoValues[str[13]] + AssoValues[str[11]] + AssoValues[str[7]] + AssoValues[@as(usize, str[6]) + 1] + AssoValues[@as(usize, str[5]) + 2] + AssoValues[@as(usize, str[4]) + 3] + AssoValues[@as(usize, str[3]) + 5] + AssoValues[@as(usize, str[2]) + 1],
    }}
    hash += AssoValues[str[1]];
    hash += AssoValues[@as(usize, str[0]) + 13];
    return hash;
}}
'''
translated_zig, count = re.subn(
    r"pub fn entity_hash\(.*?\n\}\npub const lengthtable",
    tuned_hash + "pub const lengthtable",
    translated_zig,
    count=1,
    flags=re.S,
)
if count != 1:
    raise RuntimeError("could not replace translated entity_hash")

tuned_lookup = r'''pub fn entity_lookup(str: [*c]const u8, len: usize) [*c]const struct_Entity {
    if (len < 2 or len > 32) return null;
    const key = entity_hash(str, len);
    if (key > 15511 or lengthtable[key] != len) return null;
    const stored = entity_wordlist[key].name;
    if (str[0] == stored[0] and entity_compare(str + 1, stored + 1, len - 1)) {
        return &entity_wordlist[key];
    }
    return null;
}
'''
translated_zig, count = re.subn(
    r"pub fn entity_lookup\(.*?\n\}\n\npub const __VERSION__[\s\S]*",
    tuned_lookup,
    translated_zig,
    count=1,
    flags=re.S,
)
if count != 1:
    raise RuntimeError("could not replace translated entity_lookup")
GPERF_ZIG.write_text(translated_zig)
subprocess.run(["zig", "fmt", str(GPERF_ZIG)], cwd=ROOT, check=True)

with NAMED_OUT.open("w") as out:
    out.write("// Generated by bench/entity_lookup/generate.py from the WHATWG entity table.\n")
    out.write("const std = @import(\"std\");\n")
    out.write("const gperf = @import(\"named_entities_gperf.zig\");\n")
    out.write("const ValueEntry = struct { start: u32, len: u8 };\n")
    out.write(f"pub const MaxNameLen: usize = {max(len(name) for name, _ in items)};\n")
    out.write(f"pub const MaxValueLen: usize = {max(len(value) for _, value in items)};\n")
    out.write(f"const Values = [_]u8{{{ints(value_blob)}}};\n")
    out.write("const ValueEntries = [_]ValueEntry{\n")
    for row in entries:
        out.write(f".{{.start={row[2]},.len={row[3]}}},\n")
    out.write(r'''};

pub fn lookup(name: []const u8) ?[]const u8 {
    if (name.len < 2 or name.len > MaxNameLen) return null;
    const found = gperf.entity_lookup(name.ptr, name.len);
    if (found == null) return null;
    const entry = ValueEntries[found.*.index];
    return Values[entry.start..][0..entry.len];
}

pub fn longestPrefix(rem: []const u8, comptime attribute: bool) ?struct { consumed: u8, value: []const u8 } {
    var len = @min(rem.len, MaxNameLen);
    while (len >= 2) : (len -= 1) {
        const candidate = rem[0..len];
        const value = lookup(candidate) orelse continue;
        if (comptime attribute) {
            if (candidate[candidate.len - 1] != ';' and len < rem.len and
                (std.ascii.isAlphanumeric(rem[len]) or rem[len] == '=')) continue;
        }
        return .{ .consumed = @intCast(len + 1), .value = value };
    }
    return null;
}

test "generated named entity lookup" {
    try std.testing.expectEqualStrings("\xc2\xa0", lookup("nbsp;").?);
    try std.testing.expectEqualStrings("\xe2\xaa\xa2\xcc\xb8", lookup("NotNestedGreaterGreater;").?);
}
''')

subprocess.run(["zig", "fmt", str(NAMED_OUT)], cwd=ROOT, check=True)
print(f"generated gperf lookup under {GENERATED_DIR}")
